"""agregue relacion tareas

Revision ID: fb6d7813c6d1
Revises: c1ce7d28bfdf
Create Date: 2022-11-10 19:53:52.097858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6d7813c6d1'
down_revision = 'c1ce7d28bfdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tareas', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tareas', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tareas', type_='foreignkey')
    op.drop_column('tareas', 'usuario_id')
    # ### end Alembic commands ###
